Docs Overview Oracle Cloud Infrastructure [minor change]
oracle/terraform-provider-oci pull request #1230
Opened 2020-11-11 20:46 UTC by shantanu-parate

2021-02-06 11:54 UTC, stepotronic requested changes

2021-02-06 11:54 UTC, stepotronic commented on website/docs/index.html.markdown
> + TO used a non-default profile, you can set it through environment value like: `export TF_VAR_config_file_profile=<value>` or set it in a provider block like:
```suggestion
 To use a non-default profile, you can set it through environment value like: `export TF_VAR_config_file_profile=<value>` or set it in a provider block like:
```

2023-05-24 09:52 UTC, tf-oci-pub commented
Thank you for your valuable contribution. We greatly appreciate your efforts in submitting this pull request. However, I regret to inform you that we are unable to merge it directly on GitHub at this time.

Our internal policy requires that all pull requests undergo thorough local testing and review before they can be merged into the main codebase. This process ensures the quality and stability of Terraform-Provider-OCI.

We understand that this may cause some inconvenience, but please rest assured that your contribution is highly valued. Our team will carefully review and test your changes locally to ensure they meet our standards.

We appreciate your understanding and patience in this matter. If you have any questions or need further assistance, please don't hesitate to reach out. Thank you once again for your contribution.

2023-05-30 11:31 UTC, MeharwadeDivya commented
We are merging this internally and the changes will be part of next release.

2023-05-30 11:31 UTC, closed without merging